/**
 * Seed: Sample Products and SKU Variants
 * Inserts sample products with associated SKUs.
 */
exports.seed = async function (knex) {
  await knex('skus').del();
  await knex('products').del();

  // ─── Products ────────────────────────────────────────────────────────────────

  await knex('products').insert([
    // Electronics — Smartphones
    {
      id: 1,
      category_id: 10,
      brand_id: 1,
      name: 'TechNova X12 Smartphone',
      slug: 'technova-x12-smartphone',
      description:
        'Flagship smartphone with a 6.7-inch AMOLED display, 5G connectivity, and 108 MP camera.',
      base_price: 799.99,
      is_active: true,
      is_featured: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Electronics — Laptops
    {
      id: 2,
      category_id: 11,
      brand_id: 1,
      name: 'TechNova ProBook 15',
      slug: 'technova-probook-15',
      description:
        '15.6-inch laptop with Intel Core i7, 16 GB RAM, 512 GB SSD, and all-day battery life.',
      base_price: 1249.99,
      is_active: true,
      is_featured: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Electronics — Audio
    {
      id: 3,
      category_id: 12,
      brand_id: 5,
      name: 'SoundWave ANC Pro Headphones',
      slug: 'soundwave-anc-pro-headphones',
      description:
        'Over-ear wireless headphones with active noise cancellation and 30-hour battery life.',
      base_price: 299.99,
      is_active: true,
      is_featured: false,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Clothing — Men's
    {
      id: 4,
      category_id: 20,
      brand_id: 2,
      name: "UrbanThread Men's Classic Tee",
      slug: 'urbanthread-mens-classic-tee',
      description:
        '100% organic cotton classic-fit t-shirt available in multiple colours and sizes.',
      base_price: 29.99,
      is_active: true,
      is_featured: false,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Clothing — Women's
    {
      id: 5,
      category_id: 21,
      brand_id: 2,
      name: "UrbanThread Women's Jogger Pants",
      slug: 'urbanthread-womens-jogger-pants',
      description:
        'Comfortable stretch-fabric jogger pants with tapered leg and adjustable waistband.',
      base_price: 49.99,
      is_active: true,
      is_featured: false,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Home & Garden — Furniture
    {
      id: 6,
      category_id: 30,
      brand_id: 3,
      name: 'HomeHaven Ergonomic Office Chair',
      slug: 'homehaven-ergonomic-office-chair',
      description:
        'Adjustable lumbar support office chair with breathable mesh back and armrests.',
      base_price: 349.99,
      is_active: true,
      is_featured: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Sports & Outdoors — Fitness
    {
      id: 7,
      category_id: 40,
      brand_id: 4,
      name: 'PeakGear Adjustable Dumbbell Set',
      slug: 'peakgear-adjustable-dumbbell-set',
      description:
        'Space-saving adjustable dumbbell set ranging from 5 to 52.5 lbs per dumbbell.',
      base_price: 399.99,
      is_active: true,
      is_featured: false,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Sports & Outdoors — Camping
    {
      id: 8,
      category_id: 41,
      brand_id: 4,
      name: 'PeakGear Ultralight Tent 2-Person',
      slug: 'peakgear-ultralight-tent-2-person',
      description:
        'Freestanding 2-person backpacking tent weighing only 2.1 kg with full waterproof coverage.',
      base_price: 249.99,
      is_active: true,
      is_featured: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);

  // ─── SKUs ─────────────────────────────────────────────────────────────────────

  await knex('skus').insert([
    // Product 1 — TechNova X12 Smartphone (variants: storage × colour)
    {
      id: 101,
      product_id: 1,
      sku_code: 'TN-X12-128-BLK',
      variant_options: JSON.stringify({ storage: '128 GB', colour: 'Midnight Black' }),
      price: 799.99,
      stock_quantity: 50,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 102,
      product_id: 1,
      sku_code: 'TN-X12-128-SLV',
      variant_options: JSON.stringify({ storage: '128 GB', colour: 'Arctic Silver' }),
      price: 799.99,
      stock_quantity: 35,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 103,
      product_id: 1,
      sku_code: 'TN-X12-256-BLK',
      variant_options: JSON.stringify({ storage: '256 GB', colour: 'Midnight Black' }),
      price: 899.99,
      stock_quantity: 40,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 104,
      product_id: 1,
      sku_code: 'TN-X12-256-SLV',
      variant_options: JSON.stringify({ storage: '256 GB', colour: 'Arctic Silver' }),
      price: 899.99,
      stock_quantity: 20,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 2 — TechNova ProBook 15 (variants: RAM × storage)
    {
      id: 201,
      product_id: 2,
      sku_code: 'TN-PB15-16-512',
      variant_options: JSON.stringify({ ram: '16 GB', storage: '512 GB SSD' }),
      price: 1249.99,
      stock_quantity: 25,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 202,
      product_id: 2,
      sku_code: 'TN-PB15-32-512',
      variant_options: JSON.stringify({ ram: '32 GB', storage: '512 GB SSD' }),
      price: 1449.99,
      stock_quantity: 15,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 203,
      product_id: 2,
      sku_code: 'TN-PB15-32-1TB',
      variant_options: JSON.stringify({ ram: '32 GB', storage: '1 TB SSD' }),
      price: 1649.99,
      stock_quantity: 10,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 3 — SoundWave ANC Pro Headphones (variants: colour)
    {
      id: 301,
      product_id: 3,
      sku_code: 'SW-ANCPRO-BLK',
      variant_options: JSON.stringify({ colour: 'Matte Black' }),
      price: 299.99,
      stock_quantity: 60,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 302,
      product_id: 3,
      sku_code: 'SW-ANCPRO-WHT',
      variant_options: JSON.stringify({ colour: 'Pearl White' }),
      price: 299.99,
      stock_quantity: 45,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 4 — UrbanThread Men's Classic Tee (variants: size × colour)
    {
      id: 401,
      product_id: 4,
      sku_code: 'UT-MCT-S-WHT',
      variant_options: JSON.stringify({ size: 'S', colour: 'White' }),
      price: 29.99,
      stock_quantity: 100,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 402,
      product_id: 4,
      sku_code: 'UT-MCT-M-WHT',
      variant_options: JSON.stringify({ size: 'M', colour: 'White' }),
      price: 29.99,
      stock_quantity: 120,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 403,
      product_id: 4,
      sku_code: 'UT-MCT-L-WHT',
      variant_options: JSON.stringify({ size: 'L', colour: 'White' }),
      price: 29.99,
      stock_quantity: 110,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 404,
      product_id: 4,
      sku_code: 'UT-MCT-M-BLK',
      variant_options: JSON.stringify({ size: 'M', colour: 'Black' }),
      price: 29.99,
      stock_quantity: 95,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 405,
      product_id: 4,
      sku_code: 'UT-MCT-L-BLK',
      variant_options: JSON.stringify({ size: 'L', colour: 'Black' }),
      price: 29.99,
      stock_quantity: 80,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 406,
      product_id: 4,
      sku_code: 'UT-MCT-XL-BLK',
      variant_options: JSON.stringify({ size: 'XL', colour: 'Black' }),
      price: 29.99,
      stock_quantity: 60,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 5 — UrbanThread Women's Jogger Pants (variants: size × colour)
    {
      id: 501,
      product_id: 5,
      sku_code: 'UT-WJP-XS-GRY',
      variant_options: JSON.stringify({ size: 'XS', colour: 'Heather Grey' }),
      price: 49.99,
      stock_quantity: 70,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 502,
      product_id: 5,
      sku_code: 'UT-WJP-S-GRY',
      variant_options: JSON.stringify({ size: 'S', colour: 'Heather Grey' }),
      price: 49.99,
      stock_quantity: 85,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 503,
      product_id: 5,
      sku_code: 'UT-WJP-M-GRY',
      variant_options: JSON.stringify({ size: 'M', colour: 'Heather Grey' }),
      price: 49.99,
      stock_quantity: 90,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 504,
      product_id: 5,
      sku_code: 'UT-WJP-M-NVY',
      variant_options: JSON.stringify({ size: 'M', colour: 'Navy Blue' }),
      price: 49.99,
      stock_quantity: 75,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 6 — HomeHaven Ergonomic Office Chair (variants: colour)
    {
      id: 601,
      product_id: 6,
      sku_code: 'HH-EOC-BLK',
      variant_options: JSON.stringify({ colour: 'Black' }),
      price: 349.99,
      stock_quantity: 30,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 602,
      product_id: 6,
      sku_code: 'HH-EOC-GRY',
      variant_options: JSON.stringify({ colour: 'Charcoal Grey' }),
      price: 349.99,
      stock_quantity: 20,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 7 — PeakGear Adjustable Dumbbell Set (single SKU)
    {
      id: 701,
      product_id: 7,
      sku_code: 'PG-ADS-5-52',
      variant_options: JSON.stringify({ weight_range: '5-52.5 lbs' }),
      price: 399.99,
      stock_quantity: 40,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Product 8 — PeakGear Ultralight Tent 2-Person (variants: colour)
    {
      id: 801,
      product_id: 8,
      sku_code: 'PG-ULT2-GRN',
      variant_options: JSON.stringify({ colour: 'Forest Green' }),
      price: 249.99,
      stock_quantity: 25,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 802,
      product_id: 8,
      sku_code: 'PG-ULT2-ORG',
      variant_options: JSON.stringify({ colour: 'Burnt Orange' }),
      price: 249.99,
      stock_quantity: 15,
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
