/**
 * Seed: Sample Promo Codes
 * Inserts a variety of promotional codes for testing.
 */
exports.seed = async function (knex) {
  await knex('promo_codes').del();

  await knex('promo_codes').insert([
    // Flat percentage discount, no usage limit
    {
      id: 1,
      code: 'WELCOME10',
      description: '10% off for new customers',
      discount_type: 'percentage',
      discount_value: 10.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: null,
      usage_limit: null,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Flat amount discount with minimum order
    {
      id: 2,
      code: 'SAVE20',
      description: '$20 off orders over $100',
      discount_type: 'fixed',
      discount_value: 20.00,
      minimum_order_amount: 100.00,
      maximum_discount_amount: null,
      usage_limit: null,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // High-percentage discount with a cap and limited uses
    {
      id: 3,
      code: 'FLASH25',
      description: '25% off up to $50 — limited to 200 uses',
      discount_type: 'percentage',
      discount_value: 25.00,
      minimum_order_amount: 50.00,
      maximum_discount_amount: 50.00,
      usage_limit: 200,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Expired code (for testing expired-code handling)
    {
      id: 4,
      code: 'EXPIRED50',
      description: '$50 off — expired promotional code',
      discount_type: 'fixed',
      discount_value: 50.00,
      minimum_order_amount: 150.00,
      maximum_discount_amount: null,
      usage_limit: 100,
      usage_count: 100,
      is_active: false,
      starts_at: '2023-01-01 00:00:00',
      expires_at: '2023-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Free shipping code
    {
      id: 5,
      code: 'FREESHIP',
      description: 'Free shipping on any order',
      discount_type: 'free_shipping',
      discount_value: 0.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: null,
      usage_limit: null,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Single-use VIP code
    {
      id: 6,
      code: 'VIP100',
      description: '$100 off for VIP customers — single use',
      discount_type: 'fixed',
      discount_value: 100.00,
      minimum_order_amount: 200.00,
      maximum_discount_amount: null,
      usage_limit: 1,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    // Inactive/disabled code (for testing inactive-code handling)
    {
      id: 7,
      code: 'DISABLED15',
      description: '15% off — currently disabled',
      discount_type: 'percentage',
      discount_value: 15.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: null,
      usage_limit: null,
      usage_count: 0,
      is_active: false,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
